version: "3"
services:
    db:
        image: mysql:8.0
        environment:
          MYSQL_DATABASE: advertisement
          MYSQL_ROOT_PASSWORD: 1234
#          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306

    app2:
        build: .
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/advertisement
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 1234
        ports:
          - 8080:8080
        depends_on:
          - db

    nginx:
      image: nginx:latest
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app2